import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class EvolutionPage extends javax.swing.JFrame {
    private ImageIcon evolve_icon = new ImageIcon("src\\Images\\evolve-icon.png");
    public EvolutionPage() {
        initComponents();
        this.setTitle("Evolution Page");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        evolve_button.setIcon(resizeIcon(evolve_icon, 40, 40));
        
        // displaying the first creature
        creature1_type.setIcon(resizeIcon(Creatures.owned_creatures_list.get(0).creatureTypePicture, 50, 50));
        creature1_picture.setIcon(resizeIcon(Creatures.owned_creatures_list.get(0).creaturePicture, 230, 230));
        creature1_name.setText(Creatures.owned_creatures_list.get(0).creatureName);
        creature1_el.setText(String.valueOf(Creatures.owned_creatures_list.get(0).creatureEL));
        
        // displaying the second creature
        creature2_type.setIcon(resizeIcon(Creatures.owned_creatures_list.get(1).creatureTypePicture, 50, 50));
        creature2_picture.setIcon(resizeIcon(Creatures.owned_creatures_list.get(1).creaturePicture, 230, 230));
        creature2_name.setText(Creatures.owned_creatures_list.get(1).creatureName);
        creature2_el.setText(String.valueOf(Creatures.owned_creatures_list.get(1).creatureEL));
        
        for (Creatures creature : Creatures.owned_creatures_list) {
            comboBox1.addItem(creature.creatureName);
            comboBox2.addItem(creature.creatureName);
        }
        
        // initializing the combo boxes
        comboBox1.setSelectedItem(Creatures.owned_creatures_list.get(0).creatureName);
        comboBox2.setSelectedItem(Creatures.owned_creatures_list.get(1).creatureName);
    }
    
    // Method to resize ImageIcon
    private ImageIcon resizeIcon(ImageIcon icon, int width, int height) {
        Image image = icon.getImage();
        Image resizedImage = image.getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH);
        return new ImageIcon(resizedImage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creature1_panel = new javax.swing.JPanel();
        creature1_picture = new javax.swing.JLabel();
        creature2_panel = new javax.swing.JPanel();
        creature2_picture = new javax.swing.JLabel();
        evolve_button = new javax.swing.JButton();
        mainmenu_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        creature2_type = new javax.swing.JLabel();
        creature1_type = new javax.swing.JLabel();
        comboBox1 = new javax.swing.JComboBox<>();
        comboBox2 = new javax.swing.JComboBox<>();
        creature1_el_label = new javax.swing.JLabel();
        creature1_name_label = new javax.swing.JLabel();
        creature2_el_label = new javax.swing.JLabel();
        creature2_name_label = new javax.swing.JLabel();
        creature2_el = new javax.swing.JLabel();
        creature2_name = new javax.swing.JLabel();
        creature1_el = new javax.swing.JLabel();
        creature1_name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        creature1_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        creature1_panel.setPreferredSize(new java.awt.Dimension(250, 250));

        creature1_picture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout creature1_panelLayout = new javax.swing.GroupLayout(creature1_panel);
        creature1_panel.setLayout(creature1_panelLayout);
        creature1_panelLayout.setHorizontalGroup(
            creature1_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creature1_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creature1_picture, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        creature1_panelLayout.setVerticalGroup(
            creature1_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creature1_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creature1_picture, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );

        creature2_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        creature2_panel.setPreferredSize(new java.awt.Dimension(250, 250));

        creature2_picture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout creature2_panelLayout = new javax.swing.GroupLayout(creature2_panel);
        creature2_panel.setLayout(creature2_panelLayout);
        creature2_panelLayout.setHorizontalGroup(
            creature2_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creature2_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creature2_picture, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        creature2_panelLayout.setVerticalGroup(
            creature2_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creature2_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creature2_picture, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );

        evolve_button.setPreferredSize(new java.awt.Dimension(50, 50));

        mainmenu_button.setText("Main Menu");
        mainmenu_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mainmenu_button.setPreferredSize(new java.awt.Dimension(100, 25));
        mainmenu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenu_buttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Success!");

        comboBox1.setPreferredSize(new java.awt.Dimension(100, 22));
        comboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox1ActionPerformed(evt);
            }
        });

        comboBox2.setPreferredSize(new java.awt.Dimension(100, 22));
        comboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox2ActionPerformed(evt);
            }
        });

        creature1_el_label.setText("Evolution Level:");

        creature1_name_label.setText("Name:");

        creature2_el_label.setText("Evolution Level:");

        creature2_name_label.setText("Name:");

        creature2_el.setText("level");

        creature2_name.setText("name");

        creature1_el.setText("level");

        creature1_name.setText("name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainmenu_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(creature1_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(evolve_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(creature1_type, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(creature1_name_label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(creature1_name))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(creature1_el_label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(creature1_el)))))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(creature2_type, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(creature2_name_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(creature2_name))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(creature2_el_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(creature2_el))))
                    .addComponent(creature2_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(creature2_type, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(creature1_type, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(creature1_name)
                                    .addComponent(creature1_name_label, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(creature1_el_label)
                                    .addComponent(creature1_el))
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(creature2_name_label)
                                    .addComponent(creature2_name))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(creature2_el)
                                    .addComponent(creature2_el_label))
                                .addGap(6, 6, 6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(creature1_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(creature2_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(evolve_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(mainmenu_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainmenu_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenu_buttonActionPerformed
        dispose();
        new MainMenu();
    }//GEN-LAST:event_mainmenu_buttonActionPerformed

    private void comboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox1ActionPerformed
        String selected_pokemon = (String) comboBox1.getSelectedItem();
        
        for (Creatures creature : Creatures.owned_creatures_list) {
            if (creature.creatureName.equalsIgnoreCase(selected_pokemon)) {
                creature1_type.setIcon(resizeIcon(creature.creatureTypePicture, 50, 50));
                creature1_picture.setIcon(resizeIcon(creature.creaturePicture, 230, 230));
                creature1_name.setText(creature.creatureName);
                creature1_el.setText(String.valueOf(creature.creatureEL));
            }
        }
    }//GEN-LAST:event_comboBox1ActionPerformed

    private void comboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox2ActionPerformed
        String selected_pokemon = (String) comboBox2.getSelectedItem();
        
        for (Creatures creature : Creatures.owned_creatures_list) {
            if (creature.creatureName.equalsIgnoreCase(selected_pokemon)) {
                creature2_type.setIcon(resizeIcon(creature.creatureTypePicture, 50, 50));
                creature2_picture.setIcon(resizeIcon(creature.creaturePicture, 230, 230));
                creature2_name.setText(creature.creatureName);
                creature2_el.setText(String.valueOf(creature.creatureEL));
            }
        }
    }//GEN-LAST:event_comboBox2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBox1;
    private javax.swing.JComboBox<String> comboBox2;
    private javax.swing.JLabel creature1_el;
    private javax.swing.JLabel creature1_el_label;
    private javax.swing.JLabel creature1_name;
    private javax.swing.JLabel creature1_name_label;
    private javax.swing.JPanel creature1_panel;
    private javax.swing.JLabel creature1_picture;
    private javax.swing.JLabel creature1_type;
    private javax.swing.JLabel creature2_el;
    private javax.swing.JLabel creature2_el_label;
    private javax.swing.JLabel creature2_name;
    private javax.swing.JLabel creature2_name_label;
    private javax.swing.JPanel creature2_panel;
    private javax.swing.JLabel creature2_picture;
    private javax.swing.JLabel creature2_type;
    private javax.swing.JButton evolve_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mainmenu_button;
    // End of variables declaration//GEN-END:variables
}
